export default {
  name: `services`,
  title: `Meal Services`,
  type: `document`,
  groups: [
    { name: `header`, title: `Header & Hero Texts` },
    { name: `weekly`, title: `Weekly Prepared Meals` },
    { name: `feasts`, title: `Family Feasts` },
    { name: `provisions`, title: `Provisions` },
    { name: `gift`, title: `Gift a Meal` },
  ],
  fields: [
    {
      name: `header`,
      title: `Header Text*`,
      type: `array`,
      of: [{ type: `text`, rows: 4 }],
      group: `header`,
      validation: (Rule: any) => Rule.required().min(1),
    },
    {
      name: `hero`,
      title: `Hero Text*`,
      type: `array`,
      of: [{ type: `text`, rows: 4 }],
      group: `header`,
      validation: (Rule: any) => Rule.required().min(1),
    },
    {
      name: `howItWorks`,
      title: `How It Works*`,
      type: `object`,
      fields: [
        {
          name: `list`,
          title: `List*`,
          description: `Minimum of 3 entries`,
          type: `array`,
          of: [{ type: `string` }],
          validation: (Rule: any) => Rule.required().min(3),
        },
        {
          name: `subtext`,
          title: `List Subtext`,
          description: `Notes that should be associated with list items`,
          type: `array`,
          of: [{ type: `string` }],
          validation: (Rule: any) => Rule.max(3),
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: `weekly`,
      title: `Weekly Prepared Meals*`,
      type: `object`,
      fields: [
        {
          name: `description`,
          title: `Description*`,
          type: `text`,
          rows: 2,
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: `options`,
          title: `Example Menu Options*`,
          type: `array`,
          of: [{ type: `string` }],
          validation: (Rule: any) => Rule.required().min(5),
        },
      ],
      group: `weekly`,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: `feasts`,
      title: `Family Feasts*`,
      type: `object`,
      group: `feasts`,
      fields: [
        {
          name: `description`,
          title: `Description*`,
          type: `array`,
          of: [{ type: `text`, rows: 2 }],
          validation: (Rule: any) => Rule.required().min(1),
        },
        {
          name: `pricing`,
          title: `Pricing*`,
          type: `array`,
          of: [
            {
              type: `object`,
              options: {
                columns: 2,
              },
              fields: [
                {
                  name: `type`,
                  title: `Meal Type`,
                  type: `string`,
                  validation: (Rule: any) => Rule.required(),
                },
                {
                  name: `cost`,
                  title: `Minimum Cost*`,
                  type: `number`,
                  validation: (Rule: any) => Rule.required().min(0),
                },
              ],
            },
          ],
          validation: (Rule: any) => Rule.required(),
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: `provisions`,
      title: `Provisions Description*`,
      type: `text`,
      rows: 2,
      group: `provisions`,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: `gift`,
      title: `Gift a Meal*`,
      type: `text`,
      rows: 2,
      group: `gift`,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: `testimonials`,
      title: `Testimonials`,
      type: `array`,
      of: [{ type: `reference`, to: [{ type: `testimonial` }] }],
      validation: (Rule: any) => Rule.required().max(5),
    },
  ],
};
